// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/checkpoints.proto

/* eslint-disable */

export interface CheckpointRestoreRequest {
  taskId?: string | undefined;
  number: number;
  restoreType: string;
  offset?: number | undefined;
}

export interface CheckpointSubscriptionRequest {
  cwdHash: string;
}

export interface CheckpointEvent {
  operation: CheckpointEvent_OperationType;
  cwdHash: string;
  isActive: boolean;
  timestamp: string;
  taskId?: string | undefined;
  commitHash?: string | undefined;
}

export enum CheckpointEvent_OperationType {
  CHECKPOINT_INIT = 0,
  CHECKPOINT_COMMIT = 1,
  CHECKPOINT_RESTORE = 2,
  UNRECOGNIZED = -1,
}

export function checkpointEvent_OperationTypeFromJSON(object: any): CheckpointEvent_OperationType {
  switch (object) {
    case 0:
    case "CHECKPOINT_INIT":
      return CheckpointEvent_OperationType.CHECKPOINT_INIT;
    case 1:
    case "CHECKPOINT_COMMIT":
      return CheckpointEvent_OperationType.CHECKPOINT_COMMIT;
    case 2:
    case "CHECKPOINT_RESTORE":
      return CheckpointEvent_OperationType.CHECKPOINT_RESTORE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CheckpointEvent_OperationType.UNRECOGNIZED;
  }
}

export function checkpointEvent_OperationTypeToJSON(object: CheckpointEvent_OperationType): string {
  switch (object) {
    case CheckpointEvent_OperationType.CHECKPOINT_INIT:
      return "CHECKPOINT_INIT";
    case CheckpointEvent_OperationType.CHECKPOINT_COMMIT:
      return "CHECKPOINT_COMMIT";
    case CheckpointEvent_OperationType.CHECKPOINT_RESTORE:
      return "CHECKPOINT_RESTORE";
    case CheckpointEvent_OperationType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PathHashMap {
  pathHash: { [key: string]: string };
}

export interface PathHashMap_PathHashEntry {
  key: string;
  value: string;
}
