// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/common.proto

/* eslint-disable */

export enum DiagnosticSeverity {
  DIAGNOSTIC_ERROR = 0,
  DIAGNOSTIC_WARNING = 1,
  DIAGNOSTIC_INFORMATION = 2,
  DIAGNOSTIC_HINT = 3,
  UNRECOGNIZED = -1,
}

export function diagnosticSeverityFromJSON(object: any): DiagnosticSeverity {
  switch (object) {
    case 0:
    case "DIAGNOSTIC_ERROR":
      return DiagnosticSeverity.DIAGNOSTIC_ERROR;
    case 1:
    case "DIAGNOSTIC_WARNING":
      return DiagnosticSeverity.DIAGNOSTIC_WARNING;
    case 2:
    case "DIAGNOSTIC_INFORMATION":
      return DiagnosticSeverity.DIAGNOSTIC_INFORMATION;
    case 3:
    case "DIAGNOSTIC_HINT":
      return DiagnosticSeverity.DIAGNOSTIC_HINT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DiagnosticSeverity.UNRECOGNIZED;
  }
}

export function diagnosticSeverityToJSON(object: DiagnosticSeverity): string {
  switch (object) {
    case DiagnosticSeverity.DIAGNOSTIC_ERROR:
      return "DIAGNOSTIC_ERROR";
    case DiagnosticSeverity.DIAGNOSTIC_WARNING:
      return "DIAGNOSTIC_WARNING";
    case DiagnosticSeverity.DIAGNOSTIC_INFORMATION:
      return "DIAGNOSTIC_INFORMATION";
    case DiagnosticSeverity.DIAGNOSTIC_HINT:
      return "DIAGNOSTIC_HINT";
    case DiagnosticSeverity.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FileDiagnostics {
  filePath: string;
  diagnostics: Diagnostic[];
}

export interface Diagnostic {
  message: string;
  range: DiagnosticRange | undefined;
  severity: DiagnosticSeverity;
  source?: string | undefined;
}

export interface DiagnosticRange {
  start: DiagnosticPosition | undefined;
  end: DiagnosticPosition | undefined;
}

export interface DiagnosticPosition {
  line: number;
  character: number;
}
