// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/commands.proto

/* eslint-disable */
import { Diagnostic } from "./common";

export interface CommandContext {
  /** The absolute path of the current file. */
  filePath?:
    | string
    | undefined;
  /** The selected source text. */
  selectedText?:
    | string
    | undefined;
  /** The language identifier for the current file. */
  language?:
    | string
    | undefined;
  /** Any diagnostic problems for the current file. */
  diagnostics: Diagnostic[];
}