// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/dictation.proto

/* eslint-disable */

export interface TranscribeAudioRequest {
  audioBase64: string;
  language: string;
}

export interface RecordingResult {
  success: boolean;
  error: string;
}

export interface RecordedAudio {
  success: boolean;
  audioBase64: string;
  error: string;
}

export interface RecordingStatus {
  isRecording: boolean;
  durationSeconds: number;
  error: string;
}

export interface Transcription {
  text: string;
  error: string;
}
