// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/file.proto

/* eslint-disable */

/** Enum for file search type filtering */
export enum FileSearchType {
  FILE = 0,
  FOLDER = 1,
  UNRECOGNIZED = -1,
}

export function fileSearchTypeFromJSON(object: any): FileSearchType {
  switch (object) {
    case 0:
    case "FILE":
      return FileSearchType.FILE;
    case 1:
    case "FOLDER":
      return FileSearchType.FOLDER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FileSearchType.UNRECOGNIZED;
  }
}

export function fileSearchTypeToJSON(object: FileSearchType): string {
  switch (object) {
    case FileSearchType.FILE:
      return "FILE";
    case FileSearchType.FOLDER:
      return "FOLDER";
    case FileSearchType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Response for refreshRules operation */
export interface RefreshedRules {
  globalClineRulesToggles: ClineRulesToggles | undefined;
  localClineRulesToggles: ClineRulesToggles | undefined;
  localCursorRulesToggles: ClineRulesToggles | undefined;
  localWindsurfRulesToggles: ClineRulesToggles | undefined;
  localWorkflowToggles: ClineRulesToggles | undefined;
  globalWorkflowToggles: ClineRulesToggles | undefined;
}

/** Request to toggle a Windsurf rule */
export interface ToggleWindsurfRuleRequest {
  /** Path to the rule file */
  rulePath: string;
  /** Whether to enable or disable the rule */
  enabled: boolean;
}

/** Request to convert a list of URIs to relative paths */
export interface RelativePathsRequest {
  uris: string[];
}

/** Response containing the converted relative paths */
export interface RelativePaths {
  paths: string[];
}

/** Request for file search operations */
export interface FileSearchRequest {
  /** Search query string */
  query: string;
  /** Optional request ID for tracking requests */
  mentionsRequestId?:
    | string
    | undefined;
  /** Optional limit for results (default: 20) */
  limit?:
    | number
    | undefined;
  /** Optional selected type filter */
  selectedType?:
    | FileSearchType
    | undefined;
  /** Optional workspace name to search in */
  workspaceHint?: string | undefined;
}

/** Result for file search operations */
export interface FileSearchResults {
  /** Array of file/folder results */
  results: FileInfo[];
  /** Echo of the request ID for tracking */
  mentionsRequestId?: string | undefined;
}

/** File information structure for search results */
export interface FileInfo {
  /** Relative path from workspace root */
  path: string;
  /** "file" or "folder" */
  type: string;
  /** Display name (usually basename) */
  label?:
    | string
    | undefined;
  /** Workspace this result came from */
  workspaceName?: string | undefined;
}

/** Response for searchCommits */
export interface GitCommits {
  commits: GitCommit[];
}

/** Represents a Git commit */
export interface GitCommit {
  hash: string;
  shortHash: string;
  subject: string;
  author: string;
  date: string;
}

/** Unified request for all rule file operations */
export interface RuleFileRequest {
  /** Common field for all operations */
  isGlobal: boolean;
  /** Path field for deleteRuleFile (optional) */
  rulePath?:
    | string
    | undefined;
  /** Filename field for createRuleFile (optional) */
  filename?:
    | string
    | undefined;
  /** Type of the file to create (optional) */
  type?: string | undefined;
}

/** Result for rule file operations with meaningful data only */
export interface RuleFile {
  /** Path to the rule file */
  filePath: string;
  /** Filename for display purposes */
  displayName: string;
  /** For createRuleFile, indicates if file already existed */
  alreadyExists: boolean;
}

/** Request to toggle a Cline rule */
export interface ToggleClineRuleRequest {
  /** Whether this is a global rule or workspace rule */
  isGlobal: boolean;
  /** Path to the rule file */
  rulePath: string;
  /** Whether to enable or disable the rule */
  enabled: boolean;
}

/** Maps from filepath to enabled/disabled status, matching app's ClineRulesToggles type */
export interface ClineRulesToggles {
  toggles: { [key: string]: boolean };
}

export interface ClineRulesToggles_TogglesEntry {
  key: string;
  value: boolean;
}

/** Response for toggleClineRule operation */
export interface ToggleClineRules {
  globalClineRulesToggles: ClineRulesToggles | undefined;
  localClineRulesToggles: ClineRulesToggles | undefined;
}

/** Request to toggle a Cursor rule */
export interface ToggleCursorRuleRequest {
  /** Path to the rule file */
  rulePath: string;
  /** Whether to enable or disable the rule */
  enabled: boolean;
}

/** Request to toggle a workflow on or off */
export interface ToggleWorkflowRequest {
  workflowPath: string;
  enabled: boolean;
  isGlobal: boolean;
}