// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/hooks.proto

/* eslint-disable */

/** Input message for all hooks */
export interface HookInput {
  clineVersion: string;
  hookName: string;
  timestamp: string;
  taskId: string;
  workspaceRoots: string[];
  userId: string;
  preToolUse?: PreToolUseData | undefined;
  postToolUse?: PostToolUseData | undefined;
  userPromptSubmit?: UserPromptSubmitData | undefined;
  taskStart?: TaskStartData | undefined;
  taskResume?: TaskResumeData | undefined;
  taskCancel?: TaskCancelData | undefined;
  taskComplete?: TaskCompleteData | undefined;
  preCompact?: PreCompactData | undefined;
}

/** Output message for all hooks */
export interface HookOutput {
  contextModification: string;
  shouldContinue: boolean;
  errorMessage: string;
}

/** Data for PreToolUse hook */
export interface PreToolUseData {
  toolName: string;
  parameters: { [key: string]: string };
}

export interface PreToolUseData_ParametersEntry {
  key: string;
  value: string;
}

/** Data for PostToolUse hook */
export interface PostToolUseData {
  toolName: string;
  parameters: { [key: string]: string };
  result: string;
  success: boolean;
  executionTimeMs: number;
}

export interface PostToolUseData_ParametersEntry {
  key: string;
  value: string;
}

/** Data for UserPromptSubmit hook */
export interface UserPromptSubmitData {
  prompt: string;
  attachments: string[];
}

/** Data for TaskStart hook */
export interface TaskStartData {
  taskMetadata: { [key: string]: string };
}

export interface TaskStartData_TaskMetadataEntry {
  key: string;
  value: string;
}

/** Data for TaskResume hook */
export interface TaskResumeData {
  taskMetadata: { [key: string]: string };
  previousState: { [key: string]: string };
}

export interface TaskResumeData_TaskMetadataEntry {
  key: string;
  value: string;
}

export interface TaskResumeData_PreviousStateEntry {
  key: string;
  value: string;
}

/** Data for TaskCancel hook */
export interface TaskCancelData {
  taskMetadata: { [key: string]: string };
}

export interface TaskCancelData_TaskMetadataEntry {
  key: string;
  value: string;
}

/** Data for TaskComplete hook */
export interface TaskCompleteData {
  taskMetadata: { [key: string]: string };
}

export interface TaskCompleteData_TaskMetadataEntry {
  key: string;
  value: string;
}

/** Data for PreCompact hook */
export interface PreCompactData {
  contextSize: number;
  messagesToCompact: number;
  compactionStrategy: string;
}