// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/mcp.proto

/* eslint-disable */

export enum McpServerStatus {
  /**
   * MCP_SERVER_STATUS_DISCONNECTED - Protobuf enums (in proto3) must have a zero value defined, which serves as the default if the field isn't explicitly set.
   * To align with the required nature of the TypeScript type and avoid an unnecessary UNSPECIFIED state, we map one of the existing statuses to this zero value.
   */
  MCP_SERVER_STATUS_DISCONNECTED = 0,
  MCP_SERVER_STATUS_CONNECTED = 1,
  MCP_SERVER_STATUS_CONNECTING = 2,
  UNRECOGNIZED = -1,
}

export function mcpServerStatusFromJSON(object: any): McpServerStatus {
  switch (object) {
    case 0:
    case "MCP_SERVER_STATUS_DISCONNECTED":
      return McpServerStatus.MCP_SERVER_STATUS_DISCONNECTED;
    case 1:
    case "MCP_SERVER_STATUS_CONNECTED":
      return McpServerStatus.MCP_SERVER_STATUS_CONNECTED;
    case 2:
    case "MCP_SERVER_STATUS_CONNECTING":
      return McpServerStatus.MCP_SERVER_STATUS_CONNECTING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return McpServerStatus.UNRECOGNIZED;
  }
}

export function mcpServerStatusToJSON(object: McpServerStatus): string {
  switch (object) {
    case McpServerStatus.MCP_SERVER_STATUS_DISCONNECTED:
      return "MCP_SERVER_STATUS_DISCONNECTED";
    case McpServerStatus.MCP_SERVER_STATUS_CONNECTED:
      return "MCP_SERVER_STATUS_CONNECTED";
    case McpServerStatus.MCP_SERVER_STATUS_CONNECTING:
      return "MCP_SERVER_STATUS_CONNECTING";
    case McpServerStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ToggleMcpServerRequest {
  serverName: string;
  disabled: boolean;
}

export interface UpdateMcpTimeoutRequest {
  serverName: string;
  timeout: number;
}

export interface AddRemoteMcpServerRequest {
  serverName: string;
  serverUrl: string;
}

export interface ToggleToolAutoApproveRequest {
  serverName: string;
  toolNames: string[];
  autoApprove: boolean;
}

export interface McpTool {
  name: string;
  description?: string | undefined;
  inputSchema?: string | undefined;
  autoApprove?: boolean | undefined;
}

export interface McpResource {
  uri: string;
  name: string;
  mimeType?: string | undefined;
  description?: string | undefined;
}

export interface McpResourceTemplate {
  uriTemplate: string;
  name: string;
  mimeType?: string | undefined;
  description?: string | undefined;
}

export interface McpServer {
  name: string;
  config: string;
  status: McpServerStatus;
  error?: string | undefined;
  tools: McpTool[];
  resources: McpResource[];
  resourceTemplates: McpResourceTemplate[];
  disabled?: boolean | undefined;
  timeout?: number | undefined;
}

export interface McpServers {
  mcpServers: McpServer[];
}

export interface McpMarketplaceItem {
  mcpId: string;
  githubUrl: string;
  name: string;
  author: string;
  description: string;
  codiconIcon: string;
  logoUrl: string;
  category: string;
  tags: string[];
  requiresApiKey: boolean;
  readmeContent?: string | undefined;
  llmsInstallationContent?: string | undefined;
  isRecommended: boolean;
  githubStars: number;
  downloadCount: number;
  createdAt: string;
  updatedAt: string;
  lastGithubSync: string;
}

export interface McpMarketplaceCatalog {
  items: McpMarketplaceItem[];
}

export interface McpDownloadResponse {
  mcpId: string;
  githubUrl: string;
  name: string;
  author: string;
  description: string;
  readmeContent: string;
  llmsInstallationContent: string;
  requiresApiKey: boolean;
  error?: string | undefined;
}