// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/models.proto

/* eslint-disable */

/** API Provider enumeration */
export enum ApiProvider {
  ANTHROPIC = 0,
  OPENROUTER = 1,
  BEDROCK = 2,
  VERTEX = 3,
  OPENAI = 4,
  OLLAMA = 5,
  LMSTUDIO = 6,
  GEMINI = 7,
  OPENAI_NATIVE = 8,
  REQUESTY = 9,
  TOGETHER = 10,
  DEEPSEEK = 11,
  QWEN = 12,
  DOUBAO = 13,
  MISTRAL = 14,
  VSCODE_LM = 15,
  CLINE = 16,
  LITELLM = 17,
  NEBIUS = 18,
  FIREWORKS = 19,
  ASKSAGE = 20,
  XAI = 21,
  SAMBANOVA = 22,
  CEREBRAS = 23,
  GROQ = 24,
  SAPAICORE = 25,
  CLAUDE_CODE = 26,
  MOONSHOT = 27,
  HUGGINGFACE = 28,
  HUAWEI_CLOUD_MAAS = 29,
  BASETEN = 30,
  ZAI = 31,
  VERCEL_AI_GATEWAY = 32,
  QWEN_CODE = 33,
  DIFY = 34,
  OCA = 35,
  MINIMAX = 36,
  UNRECOGNIZED = -1,
}

export function apiProviderFromJSON(object: any): ApiProvider {
  switch (object) {
    case 0:
    case "ANTHROPIC":
      return ApiProvider.ANTHROPIC;
    case 1:
    case "OPENROUTER":
      return ApiProvider.OPENROUTER;
    case 2:
    case "BEDROCK":
      return ApiProvider.BEDROCK;
    case 3:
    case "VERTEX":
      return ApiProvider.VERTEX;
    case 4:
    case "OPENAI":
      return ApiProvider.OPENAI;
    case 5:
    case "OLLAMA":
      return ApiProvider.OLLAMA;
    case 6:
    case "LMSTUDIO":
      return ApiProvider.LMSTUDIO;
    case 7:
    case "GEMINI":
      return ApiProvider.GEMINI;
    case 8:
    case "OPENAI_NATIVE":
      return ApiProvider.OPENAI_NATIVE;
    case 9:
    case "REQUESTY":
      return ApiProvider.REQUESTY;
    case 10:
    case "TOGETHER":
      return ApiProvider.TOGETHER;
    case 11:
    case "DEEPSEEK":
      return ApiProvider.DEEPSEEK;
    case 12:
    case "QWEN":
      return ApiProvider.QWEN;
    case 13:
    case "DOUBAO":
      return ApiProvider.DOUBAO;
    case 14:
    case "MISTRAL":
      return ApiProvider.MISTRAL;
    case 15:
    case "VSCODE_LM":
      return ApiProvider.VSCODE_LM;
    case 16:
    case "CLINE":
      return ApiProvider.CLINE;
    case 17:
    case "LITELLM":
      return ApiProvider.LITELLM;
    case 18:
    case "NEBIUS":
      return ApiProvider.NEBIUS;
    case 19:
    case "FIREWORKS":
      return ApiProvider.FIREWORKS;
    case 20:
    case "ASKSAGE":
      return ApiProvider.ASKSAGE;
    case 21:
    case "XAI":
      return ApiProvider.XAI;
    case 22:
    case "SAMBANOVA":
      return ApiProvider.SAMBANOVA;
    case 23:
    case "CEREBRAS":
      return ApiProvider.CEREBRAS;
    case 24:
    case "GROQ":
      return ApiProvider.GROQ;
    case 25:
    case "SAPAICORE":
      return ApiProvider.SAPAICORE;
    case 26:
    case "CLAUDE_CODE":
      return ApiProvider.CLAUDE_CODE;
    case 27:
    case "MOONSHOT":
      return ApiProvider.MOONSHOT;
    case 28:
    case "HUGGINGFACE":
      return ApiProvider.HUGGINGFACE;
    case 29:
    case "HUAWEI_CLOUD_MAAS":
      return ApiProvider.HUAWEI_CLOUD_MAAS;
    case 30:
    case "BASETEN":
      return ApiProvider.BASETEN;
    case 31:
    case "ZAI":
      return ApiProvider.ZAI;
    case 32:
    case "VERCEL_AI_GATEWAY":
      return ApiProvider.VERCEL_AI_GATEWAY;
    case 33:
    case "QWEN_CODE":
      return ApiProvider.QWEN_CODE;
    case 34:
    case "DIFY":
      return ApiProvider.DIFY;
    case 35:
    case "OCA":
      return ApiProvider.OCA;
    case 36:
    case "MINIMAX":
      return ApiProvider.MINIMAX;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ApiProvider.UNRECOGNIZED;
  }
}

export function apiProviderToJSON(object: ApiProvider): string {
  switch (object) {
    case ApiProvider.ANTHROPIC:
      return "ANTHROPIC";
    case ApiProvider.OPENROUTER:
      return "OPENROUTER";
    case ApiProvider.BEDROCK:
      return "BEDROCK";
    case ApiProvider.VERTEX:
      return "VERTEX";
    case ApiProvider.OPENAI:
      return "OPENAI";
    case ApiProvider.OLLAMA:
      return "OLLAMA";
    case ApiProvider.LMSTUDIO:
      return "LMSTUDIO";
    case ApiProvider.GEMINI:
      return "GEMINI";
    case ApiProvider.OPENAI_NATIVE:
      return "OPENAI_NATIVE";
    case ApiProvider.REQUESTY:
      return "REQUESTY";
    case ApiProvider.TOGETHER:
      return "TOGETHER";
    case ApiProvider.DEEPSEEK:
      return "DEEPSEEK";
    case ApiProvider.QWEN:
      return "QWEN";
    case ApiProvider.DOUBAO:
      return "DOUBAO";
    case ApiProvider.MISTRAL:
      return "MISTRAL";
    case ApiProvider.VSCODE_LM:
      return "VSCODE_LM";
    case ApiProvider.CLINE:
      return "CLINE";
    case ApiProvider.LITELLM:
      return "LITELLM";
    case ApiProvider.NEBIUS:
      return "NEBIUS";
    case ApiProvider.FIREWORKS:
      return "FIREWORKS";
    case ApiProvider.ASKSAGE:
      return "ASKSAGE";
    case ApiProvider.XAI:
      return "XAI";
    case ApiProvider.SAMBANOVA:
      return "SAMBANOVA";
    case ApiProvider.CEREBRAS:
      return "CEREBRAS";
    case ApiProvider.GROQ:
      return "GROQ";
    case ApiProvider.SAPAICORE:
      return "SAPAICORE";
    case ApiProvider.CLAUDE_CODE:
      return "CLAUDE_CODE";
    case ApiProvider.MOONSHOT:
      return "MOONSHOT";
    case ApiProvider.HUGGINGFACE:
      return "HUGGINGFACE";
    case ApiProvider.HUAWEI_CLOUD_MAAS:
      return "HUAWEI_CLOUD_MAAS";
    case ApiProvider.BASETEN:
      return "BASETEN";
    case ApiProvider.ZAI:
      return "ZAI";
    case ApiProvider.VERCEL_AI_GATEWAY:
      return "VERCEL_AI_GATEWAY";
    case ApiProvider.QWEN_CODE:
      return "QWEN_CODE";
    case ApiProvider.DIFY:
      return "DIFY";
    case ApiProvider.OCA:
      return "OCA";
    case ApiProvider.MINIMAX:
      return "MINIMAX";
    case ApiProvider.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** List of VS Code LM models */
export interface VsCodeLmModelsArray {
  models: LanguageModelChatSelector[];
}

/** Structure representing a language model chat selector */
export interface LanguageModelChatSelector {
  vendor?: string | undefined;
  family?: string | undefined;
  version?: string | undefined;
  id?: string | undefined;
}

/** Price tier for tiered pricing models */
export interface PriceTier {
  /** Upper limit (inclusive) of input tokens for this price */
  tokenLimit: number;
  /** Price per million tokens for this tier */
  price: number;
}

/** Thinking configuration for models that support thinking/reasoning */
export interface ThinkingConfig {
  /** Max allowed thinking budget tokens */
  maxBudget?:
    | number
    | undefined;
  /** Output price per million tokens when budget > 0 */
  outputPrice?:
    | number
    | undefined;
  /** Optional: Tiered output price when budget > 0 */
  outputPriceTiers: PriceTier[];
}

/** Model tier for tiered pricing structures */
export interface ModelTier {
  contextWindow: number;
  inputPrice?: number | undefined;
  outputPrice?: number | undefined;
  cacheWritesPrice?: number | undefined;
  cacheReadsPrice?: number | undefined;
}

/** For OpenRouterCompatibleModelInfo structure in OpenRouterModels */
export interface OpenRouterModelInfo {
  maxTokens?: number | undefined;
  contextWindow?: number | undefined;
  supportsImages?: boolean | undefined;
  supportsPromptCache: boolean;
  inputPrice?: number | undefined;
  outputPrice?: number | undefined;
  cacheWritesPrice?: number | undefined;
  cacheReadsPrice?: number | undefined;
  description?: string | undefined;
  thinkingConfig?: ThinkingConfig | undefined;
  supportsGlobalEndpoint?: boolean | undefined;
  tiers: ModelTier[];
}

/** Shared response message for model information */
export interface OpenRouterCompatibleModelInfo {
  models: { [key: string]: OpenRouterModelInfo };
}

export interface OpenRouterCompatibleModelInfo_ModelsEntry {
  key: string;
  value: OpenRouterModelInfo | undefined;
}

/** Request for fetching OpenAI models */
export interface OpenAiModelsRequest {
  baseUrl: string;
  apiKey: string;
}

/** Request for fetching SAP AI Core models */
export interface SapAiCoreModelsRequest {
  clientId: string;
  clientSecret: string;
  baseUrl: string;
  tokenUrl: string;
  resourceGroup: string;
}

/** SAP AI Core model with deployment information */
export interface SapAiCoreModelDeployment {
  modelName: string;
  deploymentId: string;
}

/** Response for SAP AI Core models with orchestration availability */
export interface SapAiCoreModelsResponse {
  deployments: SapAiCoreModelDeployment[];
  orchestrationAvailable: boolean;
}

/** Request for updating API configuration */
export interface UpdateApiConfigurationRequest {
  apiConfiguration: ModelsApiConfiguration | undefined;
}

/**
 * Request for partially updating API configuration using FieldMask
 * Only fields specified in update_mask will be updated from api_configuration
 */
export interface UpdateApiConfigurationPartialRequest {
  /**
   * The API configuration with values to update.
   * Only fields listed in update_mask will be applied from this configuration.
   */
  apiConfiguration:
    | ModelsApiConfiguration
    | undefined;
  /**
   * Mask specifying which top-level fields from api_configuration to update.
   * Field names should use camelCase (e.g., "apiKey", "planModeApiProvider").
   * If a field is in the mask but not set in api_configuration, it will be cleared (set to undefined).
   */
  updateMask: string[] | undefined;
}

/** Model info for OCA (OpenAI-compatible) models exposed by the OCA provider */
export interface OcaModelInfo {
  /** Maximum completion tokens per request supported by this model */
  maxTokens?:
    | number
    | undefined;
  /** Total context window in tokens (input + output) */
  contextWindow?:
    | number
    | undefined;
  /** Whether the model supports image inputs */
  supportsImages?:
    | boolean
    | undefined;
  /** Whether prompt caching is supported for this model */
  supportsPromptCache: boolean;
  /** Price per million input tokens (USD unless otherwise specified by provider) */
  inputPrice?:
    | number
    | undefined;
  /** Price per million output tokens (USD unless otherwise specified by provider) */
  outputPrice?:
    | number
    | undefined;
  /** Thinking/reasoning configuration if the model supports it */
  thinkingConfig?:
    | ThinkingConfig
    | undefined;
  /** Price per million tokens for prompt cache writes */
  cacheWritesPrice?:
    | number
    | undefined;
  /** Price per million tokens for prompt cache reads */
  cacheReadsPrice?:
    | number
    | undefined;
  /** Human-readable model description */
  description?:
    | string
    | undefined;
  /** Recommended default temperature for this model */
  temperature?:
    | number
    | undefined;
  /** Optional survey content to display in the UI */
  surveyContent?:
    | string
    | undefined;
  /** Identifier for the survey associated with this model */
  surveyId?:
    | string
    | undefined;
  /** Optional banner content (e.g., deprecation or promotion notes) */
  banner?:
    | string
    | undefined;
  /** Canonical model identifier as reported by OCA */
  modelName: string;
}

/** Aggregated OCA model catalog keyed by model identifier */
export interface OcaCompatibleModelInfo {
  /**
   * key: canonical model id as reported by OCA (e.g., "openai/gpt-4o-mini")
   * value: OcaModelInfo describing that model
   */
  models: { [key: string]: OcaModelInfo };
  error?: string | undefined;
}

export interface OcaCompatibleModelInfo_ModelsEntry {
  key: string;
  value: OcaModelInfo | undefined;
}

/** Model info for OpenAI-compatible models */
export interface OpenAiCompatibleModelInfo {
  maxTokens?: number | undefined;
  contextWindow?: number | undefined;
  supportsImages?: boolean | undefined;
  supportsPromptCache: boolean;
  inputPrice?: number | undefined;
  outputPrice?: number | undefined;
  thinkingConfig?: ThinkingConfig | undefined;
  supportsGlobalEndpoint?: boolean | undefined;
  cacheWritesPrice?: number | undefined;
  cacheReadsPrice?: number | undefined;
  description?: string | undefined;
  tiers: ModelTier[];
  temperature?: number | undefined;
  isR1FormatRequired?: boolean | undefined;
}

/** Model info for LiteLLM models */
export interface LiteLLMModelInfo {
  maxTokens?: number | undefined;
  contextWindow?: number | undefined;
  supportsImages?: boolean | undefined;
  supportsPromptCache: boolean;
  inputPrice?: number | undefined;
  outputPrice?: number | undefined;
  thinkingConfig?: ThinkingConfig | undefined;
  supportsGlobalEndpoint?: boolean | undefined;
  cacheWritesPrice?: number | undefined;
  cacheReadsPrice?: number | undefined;
  description?: string | undefined;
  tiers: ModelTier[];
  temperature?: number | undefined;
}

/** Main ApiConfiguration message */
export interface ModelsApiConfiguration {
  /** Global configuration fields (not mode-specific) */
  apiKey?: string | undefined;
  clineApiKey?: string | undefined;
  ulid?: string | undefined;
  liteLlmBaseUrl?: string | undefined;
  liteLlmApiKey?: string | undefined;
  liteLlmUsePromptCache?: boolean | undefined;
  openAiHeaders: { [key: string]: string };
  anthropicBaseUrl?: string | undefined;
  openRouterApiKey?: string | undefined;
  openRouterProviderSorting?: string | undefined;
  awsAccessKey?: string | undefined;
  awsSecretKey?: string | undefined;
  awsSessionToken?: string | undefined;
  awsRegion?: string | undefined;
  awsUseCrossRegionInference?: boolean | undefined;
  awsBedrockUsePromptCache?: boolean | undefined;
  awsUseProfile?: boolean | undefined;
  awsProfile?: string | undefined;
  awsBedrockEndpoint?: string | undefined;
  claudeCodePath?: string | undefined;
  vertexProjectId?: string | undefined;
  vertexRegion?: string | undefined;
  openAiBaseUrl?: string | undefined;
  openAiApiKey?: string | undefined;
  ollamaBaseUrl?: string | undefined;
  ollamaApiOptionsCtxNum?: string | undefined;
  lmStudioBaseUrl?: string | undefined;
  geminiApiKey?: string | undefined;
  geminiBaseUrl?: string | undefined;
  openAiNativeApiKey?: string | undefined;
  deepSeekApiKey?: string | undefined;
  requestyApiKey?: string | undefined;
  requestyBaseUrl?: string | undefined;
  togetherApiKey?: string | undefined;
  fireworksApiKey?: string | undefined;
  fireworksModelMaxCompletionTokens?: number | undefined;
  fireworksModelMaxTokens?: number | undefined;
  qwenApiKey?: string | undefined;
  doubaoApiKey?: string | undefined;
  mistralApiKey?: string | undefined;
  azureApiVersion?: string | undefined;
  qwenApiLine?: string | undefined;
  nebiusApiKey?: string | undefined;
  asksageApiUrl?: string | undefined;
  asksageApiKey?: string | undefined;
  xaiApiKey?: string | undefined;
  sambanovaApiKey?: string | undefined;
  cerebrasApiKey?: string | undefined;
  requestTimeoutMs?: number | undefined;
  sapAiCoreClientId?: string | undefined;
  sapAiCoreClientSecret?: string | undefined;
  sapAiResourceGroup?: string | undefined;
  sapAiCoreTokenUrl?: string | undefined;
  sapAiCoreBaseUrl?: string | undefined;
  sapAiCoreUseOrchestrationMode?: boolean | undefined;
  moonshotApiKey?: string | undefined;
  moonshotApiLine?: string | undefined;
  awsAuthentication?: string | undefined;
  awsBedrockApiKey?: string | undefined;
  clineAccountId?: string | undefined;
  groqApiKey?: string | undefined;
  huggingFaceApiKey?: string | undefined;
  huaweiCloudMaasApiKey?: string | undefined;
  basetenApiKey?: string | undefined;
  ollamaApiKey?: string | undefined;
  zaiApiKey?: string | undefined;
  zaiApiLine?: string | undefined;
  lmStudioMaxTokens?: string | undefined;
  vercelAiGatewayApiKey?: string | undefined;
  qwenCodeOauthPath?: string | undefined;
  difyApiKey?: string | undefined;
  difyBaseUrl?: string | undefined;
  ocaBaseUrl?: string | undefined;
  ocaApiKey?: string | undefined;
  ocaRefreshToken?: string | undefined;
  ocaMode?: string | undefined;
  awsUseGlobalInference?: boolean | undefined;
  minimaxApiKey?: string | undefined;
  minimaxApiLine?:
    | string
    | undefined;
  /** Plan mode configurations */
  planModeApiProvider?: ApiProvider | undefined;
  planModeApiModelId?: string | undefined;
  planModeThinkingBudgetTokens?: number | undefined;
  planModeReasoningEffort?: string | undefined;
  planModeVsCodeLmModelSelector?: LanguageModelChatSelector | undefined;
  planModeAwsBedrockCustomSelected?: boolean | undefined;
  planModeAwsBedrockCustomModelBaseId?: string | undefined;
  planModeOpenRouterModelId?: string | undefined;
  planModeOpenRouterModelInfo?: OpenRouterModelInfo | undefined;
  planModeOpenAiModelId?: string | undefined;
  planModeOpenAiModelInfo?: OpenAiCompatibleModelInfo | undefined;
  planModeOllamaModelId?: string | undefined;
  planModeLmStudioModelId?: string | undefined;
  planModeLiteLlmModelId?: string | undefined;
  planModeLiteLlmModelInfo?: LiteLLMModelInfo | undefined;
  planModeRequestyModelId?: string | undefined;
  planModeRequestyModelInfo?: OpenRouterModelInfo | undefined;
  planModeTogetherModelId?: string | undefined;
  planModeFireworksModelId?: string | undefined;
  planModeSapAiCoreModelId?: string | undefined;
  planModeSapAiCoreDeploymentId?: string | undefined;
  planModeGroqModelId?: string | undefined;
  planModeGroqModelInfo?: OpenRouterModelInfo | undefined;
  planModeHuggingFaceModelId?: string | undefined;
  planModeHuggingFaceModelInfo?: OpenRouterModelInfo | undefined;
  planModeHuaweiCloudMaasModelId?: string | undefined;
  planModeHuaweiCloudMaasModelInfo?: OpenRouterModelInfo | undefined;
  planModeBasetenModelId?: string | undefined;
  planModeBasetenModelInfo?: OpenRouterModelInfo | undefined;
  planModeVercelAiGatewayModelId?: string | undefined;
  planModeVercelAiGatewayModelInfo?: OpenRouterModelInfo | undefined;
  planModeOcaModelId?: string | undefined;
  planModeOcaModelInfo?:
    | OcaModelInfo
    | undefined;
  /** Act mode configurations */
  actModeApiProvider?: ApiProvider | undefined;
  actModeApiModelId?: string | undefined;
  actModeThinkingBudgetTokens?: number | undefined;
  actModeReasoningEffort?: string | undefined;
  actModeVsCodeLmModelSelector?: LanguageModelChatSelector | undefined;
  actModeAwsBedrockCustomSelected?: boolean | undefined;
  actModeAwsBedrockCustomModelBaseId?: string | undefined;
  actModeOpenRouterModelId?: string | undefined;
  actModeOpenRouterModelInfo?: OpenRouterModelInfo | undefined;
  actModeOpenAiModelId?: string | undefined;
  actModeOpenAiModelInfo?: OpenAiCompatibleModelInfo | undefined;
  actModeOllamaModelId?: string | undefined;
  actModeLmStudioModelId?: string | undefined;
  actModeLiteLlmModelId?: string | undefined;
  actModeLiteLlmModelInfo?: LiteLLMModelInfo | undefined;
  actModeRequestyModelId?: string | undefined;
  actModeRequestyModelInfo?: OpenRouterModelInfo | undefined;
  actModeTogetherModelId?: string | undefined;
  actModeFireworksModelId?: string | undefined;
  actModeSapAiCoreModelId?: string | undefined;
  actModeSapAiCoreDeploymentId?: string | undefined;
  actModeGroqModelId?: string | undefined;
  actModeGroqModelInfo?: OpenRouterModelInfo | undefined;
  actModeHuggingFaceModelId?: string | undefined;
  actModeHuggingFaceModelInfo?: OpenRouterModelInfo | undefined;
  actModeHuaweiCloudMaasModelId?: string | undefined;
  actModeHuaweiCloudMaasModelInfo?: OpenRouterModelInfo | undefined;
  actModeBasetenModelId?: string | undefined;
  actModeBasetenModelInfo?: OpenRouterModelInfo | undefined;
  actModeVercelAiGatewayModelId?: string | undefined;
  actModeVercelAiGatewayModelInfo?: OpenRouterModelInfo | undefined;
  actModeOcaModelId?: string | undefined;
  actModeOcaModelInfo?: OcaModelInfo | undefined;
}

export interface ModelsApiConfiguration_OpenAiHeadersEntry {
  key: string;
  value: string;
}