// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: cline/state.proto

/* eslint-disable */
import { BrowserSettings, Viewport } from "./browser";
import {
  ApiProvider,
  apiProviderFromJSON,
  apiProviderToJSON,
  LanguageModelChatSelector,
  LiteLLMModelInfo,
  ModelsApiConfiguration,
  OcaModelInfo,
  OpenAiCompatibleModelInfo,
  OpenRouterModelInfo,
} from "./models";

export enum PlanActMode {
  PLAN = 0,
  ACT = 1,
  UNRECOGNIZED = -1,
}

export function planActModeFromJSON(object: any): PlanActMode {
  switch (object) {
    case 0:
    case "PLAN":
      return PlanActMode.PLAN;
    case 1:
    case "ACT":
      return PlanActMode.ACT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PlanActMode.UNRECOGNIZED;
  }
}

export function planActModeToJSON(object: PlanActMode): string {
  switch (object) {
    case PlanActMode.PLAN:
      return "PLAN";
    case PlanActMode.ACT:
      return "ACT";
    case PlanActMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OpenaiReasoningEffort {
  LOW = 0,
  MEDIUM = 1,
  HIGH = 2,
  MINIMAL = 3,
  UNRECOGNIZED = -1,
}

export function openaiReasoningEffortFromJSON(object: any): OpenaiReasoningEffort {
  switch (object) {
    case 0:
    case "LOW":
      return OpenaiReasoningEffort.LOW;
    case 1:
    case "MEDIUM":
      return OpenaiReasoningEffort.MEDIUM;
    case 2:
    case "HIGH":
      return OpenaiReasoningEffort.HIGH;
    case 3:
    case "MINIMAL":
      return OpenaiReasoningEffort.MINIMAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OpenaiReasoningEffort.UNRECOGNIZED;
  }
}

export function openaiReasoningEffortToJSON(object: OpenaiReasoningEffort): string {
  switch (object) {
    case OpenaiReasoningEffort.LOW:
      return "LOW";
    case OpenaiReasoningEffort.MEDIUM:
      return "MEDIUM";
    case OpenaiReasoningEffort.HIGH:
      return "HIGH";
    case OpenaiReasoningEffort.MINIMAL:
      return "MINIMAL";
    case OpenaiReasoningEffort.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum McpDisplayMode {
  RICH = 0,
  PLAIN = 1,
  MARKDOWN = 2,
  UNRECOGNIZED = -1,
}

export function mcpDisplayModeFromJSON(object: any): McpDisplayMode {
  switch (object) {
    case 0:
    case "RICH":
      return McpDisplayMode.RICH;
    case 1:
    case "PLAIN":
      return McpDisplayMode.PLAIN;
    case 2:
    case "MARKDOWN":
      return McpDisplayMode.MARKDOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return McpDisplayMode.UNRECOGNIZED;
  }
}

export function mcpDisplayModeToJSON(object: McpDisplayMode): string {
  switch (object) {
    case McpDisplayMode.RICH:
      return "RICH";
    case McpDisplayMode.PLAIN:
      return "PLAIN";
    case McpDisplayMode.MARKDOWN:
      return "MARKDOWN";
    case McpDisplayMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TelemetrySettingEnum {
  UNSET = 0,
  ENABLED = 1,
  DISABLED = 2,
  UNRECOGNIZED = -1,
}

export function telemetrySettingEnumFromJSON(object: any): TelemetrySettingEnum {
  switch (object) {
    case 0:
    case "UNSET":
      return TelemetrySettingEnum.UNSET;
    case 1:
    case "ENABLED":
      return TelemetrySettingEnum.ENABLED;
    case 2:
    case "DISABLED":
      return TelemetrySettingEnum.DISABLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TelemetrySettingEnum.UNRECOGNIZED;
  }
}

export function telemetrySettingEnumToJSON(object: TelemetrySettingEnum): string {
  switch (object) {
    case TelemetrySettingEnum.UNSET:
      return "UNSET";
    case TelemetrySettingEnum.ENABLED:
      return "ENABLED";
    case TelemetrySettingEnum.DISABLED:
      return "DISABLED";
    case TelemetrySettingEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AutoApprovalActions {
  readFiles?: boolean | undefined;
  readFilesExternally?: boolean | undefined;
  editFiles?: boolean | undefined;
  editFilesExternally?: boolean | undefined;
  executeSafeCommands?: boolean | undefined;
  executeAllCommands?: boolean | undefined;
  useBrowser?: boolean | undefined;
  useMcp?: boolean | undefined;
}

/** Auto approval settings for task execution */
export interface AutoApprovalSettings {
  version: number;
  enabled: boolean;
  actions: AutoApprovalActions | undefined;
  maxRequests: number;
  enableNotifications: boolean;
  favorites: string[];
}

export interface Secrets {
  apiKeys?: Record<string, string> | undefined;
  clineAccountId?: string | undefined;
  clineClineAccountId?: string | undefined;
  authNonce?: string | undefined;
  awsAccessKey?: string | undefined;
  awsSecretKey?: string | undefined;
  awsSessionToken?: string | undefined;
  awsBedrockApiKey?: string | undefined;
  sapAiCoreClientId?: string | undefined;
  sapAiCoreClientSecret?: string | undefined;
  ocaRefreshToken?: string | undefined;
}

export interface Settings {
  awsRegion?: string | undefined;
  awsUseCrossRegionInference?: boolean | undefined;
  awsBedrockUsePromptCache?: boolean | undefined;
  awsBedrockEndpoint?: string | undefined;
  awsProfile?: string | undefined;
  awsAuthentication?: string | undefined;
  awsUseProfile?: boolean | undefined;
  vertexProjectId?: string | undefined;
  vertexRegion?: string | undefined;
  requestyBaseUrl?: string | undefined;
  openAiBaseUrl?:
    | string
    | undefined;
  /** map<string, string> open_ai_headers = 12; */
  ollamaBaseUrl?: string | undefined;
  ollamaApiOptionsCtxNum?: string | undefined;
  lmStudioBaseUrl?: string | undefined;
  lmStudioMaxTokens?: string | undefined;
  anthropicBaseUrl?: string | undefined;
  geminiBaseUrl?: string | undefined;
  azureApiVersion?: string | undefined;
  openRouterProviderSorting?: string | undefined;
  autoApprovalSettings?: AutoApprovalSettings | undefined;
  browserSettings?: BrowserSettings | undefined;
  liteLlmBaseUrl?: string | undefined;
  liteLlmUsePromptCache?: boolean | undefined;
  fireworksModelMaxCompletionTokens?: number | undefined;
  fireworksModelMaxTokens?: number | undefined;
  qwenApiLine?: string | undefined;
  moonshotApiLine?: string | undefined;
  zaiApiLine?: string | undefined;
  telemetrySetting?: string | undefined;
  asksageApiUrl?: string | undefined;
  planActSeparateModelsSetting?: boolean | undefined;
  enableCheckpointsSetting?: boolean | undefined;
  requestTimeoutMs?: number | undefined;
  shellIntegrationTimeout?: number | undefined;
  defaultTerminalProfile?: string | undefined;
  terminalOutputLineLimit?: number | undefined;
  sapAiCoreTokenUrl?: string | undefined;
  sapAiCoreBaseUrl?: string | undefined;
  sapAiResourceGroup?: string | undefined;
  sapAiCoreUseOrchestrationMode?: boolean | undefined;
  claudeCodePath?: string | undefined;
  qwenCodeOauthPath?: string | undefined;
  strictPlanModeEnabled?: boolean | undefined;
  yoloModeToggled?: boolean | undefined;
  useAutoCondense?: boolean | undefined;
  preferredLanguage?: string | undefined;
  openaiReasoningEffort?: OpenaiReasoningEffort | undefined;
  mode?: PlanActMode | undefined;
  dictationSettings?: DictationSettings | undefined;
  focusChainSettings?: FocusChainSettings | undefined;
  customPrompt?: string | undefined;
  difyBaseUrl?: string | undefined;
  autoCondenseThreshold?: number | undefined;
  ocaBaseUrl?: string | undefined;
  planModeApiProvider?: ApiProvider | undefined;
  planModeApiModelId?: string | undefined;
  planModeThinkingBudgetTokens?: number | undefined;
  planModeReasoningEffort?: string | undefined;
  planModeVsCodeLmModelSelector?: LanguageModelChatSelector | undefined;
  planModeAwsBedrockCustomSelected?: boolean | undefined;
  planModeAwsBedrockCustomModelBaseId?: string | undefined;
  planModeOpenRouterModelId?: string | undefined;
  planModeOpenRouterModelInfo?: OpenRouterModelInfo | undefined;
  planModeOpenAiModelId?: string | undefined;
  planModeOpenAiModelInfo?: OpenAiCompatibleModelInfo | undefined;
  planModeOllamaModelId?: string | undefined;
  planModeLmStudioModelId?: string | undefined;
  planModeLiteLlmModelId?: string | undefined;
  planModeLiteLlmModelInfo?: LiteLLMModelInfo | undefined;
  planModeRequestyModelId?: string | undefined;
  planModeRequestyModelInfo?: OpenRouterModelInfo | undefined;
  planModeTogetherModelId?: string | undefined;
  planModeFireworksModelId?: string | undefined;
  planModeSapAiCoreModelId?: string | undefined;
  planModeSapAiCoreDeploymentId?: string | undefined;
  planModeGroqModelId?: string | undefined;
  planModeGroqModelInfo?: OpenRouterModelInfo | undefined;
  planModeBasetenModelId?: string | undefined;
  planModeBasetenModelInfo?: OpenRouterModelInfo | undefined;
  planModeHuggingFaceModelId?: string | undefined;
  planModeHuggingFaceModelInfo?: OpenRouterModelInfo | undefined;
  planModeHuaweiCloudMaasModelId?: string | undefined;
  planModeHuaweiCloudMaasModelInfo?: OpenRouterModelInfo | undefined;
  planModeOcaModelId?: string | undefined;
  planModeOcaModelInfo?: OcaModelInfo | undefined;
  actModeApiProvider?: ApiProvider | undefined;
  actModeApiModelId?: string | undefined;
  actModeThinkingBudgetTokens?: number | undefined;
  actModeReasoningEffort?: string | undefined;
  actModeVsCodeLmModelSelector?: LanguageModelChatSelector | undefined;
  actModeAwsBedrockCustomSelected?: boolean | undefined;
  actModeAwsBedrockCustomModelBaseId?: string | undefined;
  actModeOpenRouterModelId?: string | undefined;
  actModeOpenRouterModelInfo?: OpenRouterModelInfo | undefined;
  actModeOpenAiModelId?: string | undefined;
  actModeOpenAiModelInfo?: OpenAiCompatibleModelInfo | undefined;
  actModeOllamaModelId?: string | undefined;
  actModeLmStudioModelId?: string | undefined;
  actModeLiteLlmModelId?: string | undefined;
  actModeLiteLlmModelInfo?: LiteLLMModelInfo | undefined;
  actModeRequestyModelId?: string | undefined;
  actModeRequestyModelInfo?: OpenRouterModelInfo | undefined;
  actModeTogetherModelId?: string | undefined;
  actModeFireworksModelId?: string | undefined;
  actModeSapAiCoreModelId?: string | undefined;
  actModeSapAiCoreDeploymentId?: string | undefined;
  actModeGroqModelId?: string | undefined;
  actModeGroqModelInfo?: OpenRouterModelInfo | undefined;
  actModeBasetenModelId?: string | undefined;
  actModeBasetenModelInfo?: OpenRouterModelInfo | undefined;
  actModeHuggingFaceModelId?: string | undefined;
  actModeHuggingFaceModelInfo?: OpenRouterModelInfo | undefined;
  actModeHuaweiCloudMaasModelId?: string | undefined;
  actModeHuaweiCloudMaasModelInfo?: OpenRouterModelInfo | undefined;
  planModeVercelAiGatewayModelId?: string | undefined;
  planModeVercelAiGatewayModelInfo?: OpenRouterModelInfo | undefined;
  actModeVercelAiGatewayModelId?: string | undefined;
  actModeVercelAiGatewayModelInfo?: OpenRouterModelInfo | undefined;
  actModeOcaModelId?: string | undefined;
  actModeOcaModelInfo?: OcaModelInfo | undefined;
  maxConsecutiveMistakes?: number | undefined;
  subagentsEnabled?: boolean | undefined;
  subagentTerminalOutputLineLimit?: number | undefined;
}

export interface DictationSettings {
  featureEnabled: boolean;
  dictationEnabled: boolean;
  dictationLanguage: string;
}

export interface State {
  stateJson: string;
}

export interface TerminalProfiles {
  profiles: TerminalProfile[];
}

export interface TerminalProfile {
  id: string;
  name: string;
  path?: string | undefined;
  description?: string | undefined;
}

export interface TerminalProfileUpdateResponse {
  closedCount: number;
  busyTerminalsCount: number;
  hasBusyTerminals: boolean;
}

export interface TogglePlanActModeRequest {
  mode: PlanActMode;
  chatContent?: ChatContent | undefined;
}

export interface ChatContent {
  message?: string | undefined;
  images: string[];
  files: string[];
}

export interface ResetStateRequest {
  global?: boolean | undefined;
}

export interface AutoApprovalSettingsRequest {
  version: number;
  enabled: boolean;
  actions: AutoApprovalActions | undefined;
  maxRequests: number;
  enableNotifications: boolean;
  favorites: string[];
}

export interface TelemetrySettingRequest {
  setting: TelemetrySettingEnum;
}

/** Browser settings for UpdateSettingsRequest */
export interface BrowserSettingsUpdate {
  viewport?: Viewport | undefined;
  remoteBrowserHost?: string | undefined;
  remoteBrowserEnabled?: boolean | undefined;
  chromeExecutablePath?: string | undefined;
  disableToolUse?: boolean | undefined;
  customArgs?: string | undefined;
}

export interface UpdateSettingsRequestCli {
  settings?: Settings | undefined;
  secrets?: Secrets | undefined;
  environment?: string | undefined;
}

export interface UpdateTaskSettingsRequest {
  settings?: Settings | undefined;
  taskId?: string | undefined;
}

/** Message for updating settings */
export interface UpdateSettingsRequest {
  apiConfiguration?: ModelsApiConfiguration | undefined;
  telemetrySetting?: string | undefined;
  planActSeparateModelsSetting?: boolean | undefined;
  enableCheckpointsSetting?: boolean | undefined;
  mcpMarketplaceEnabled?: boolean | undefined;
  shellIntegrationTimeout?: number | undefined;
  terminalReuseEnabled?: boolean | undefined;
  mcpResponsesCollapsed?: boolean | undefined;
  mcpDisplayMode?: McpDisplayMode | undefined;
  terminalOutputLineLimit?: number | undefined;
  mode?: PlanActMode | undefined;
  preferredLanguage?: string | undefined;
  openaiReasoningEffort?: OpenaiReasoningEffort | undefined;
  strictPlanModeEnabled?: boolean | undefined;
  focusChainSettings?: FocusChainSettings | undefined;
  useAutoCondense?: boolean | undefined;
  customPrompt?: string | undefined;
  browserSettings?: BrowserSettingsUpdate | undefined;
  defaultTerminalProfile?: string | undefined;
  yoloModeToggled?: boolean | undefined;
  dictationSettings?: DictationSettings | undefined;
  autoCondenseThreshold?: number | undefined;
  multiRootEnabled?: boolean | undefined;
  hooksEnabled?: boolean | undefined;
  vscodeTerminalExecutionMode?: string | undefined;
  maxConsecutiveMistakes?: number | undefined;
  subagentsEnabled?: boolean | undefined;
  subagentTerminalOutputLineLimit?: number | undefined;
  clineEnv?: string | undefined;
}

export interface UpdateTerminalConnectionTimeoutRequest {
  timeoutMs?: number | undefined;
}

export interface FocusChainSettings {
  enabled: boolean;
  remindClineInterval: number;
}

export interface UpdateTerminalConnectionTimeoutResponse {
  timeoutMs?: number | undefined;
}

export interface ProcessInfo {
  processId: number;
  version?: string | undefined;
  uptimeMs?: number | undefined;
}