package com.hhoa.kline.core.subscription;

public enum MessageType {
    PARTIAL_MESSAGE,
    STATE,
    CHAT_BUTTON_CLICKED,
    WINDOW_SHOW_MESSAGE,
    WINDOW_SHOW_TEXT_DOCUMENT,
    WORKSPACE_OPEN_PROBLEMS_PANEL,
    WORKSPACE_OPEN_TERMINAL,
    WORKSPACE_GET_WORKSPACE_PROBLEM,
    WORKSPACE_OPEN_IN_FILE_EXPLORER_PANEL,
}
