// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.19.1
// source: host/diff.proto

/* eslint-disable */

export interface OpenDiffRequest {
  /** The absolute path of the document being edited. */
  path?:
    | string
    | undefined;
  /** The new content for the file. */
  content?: string | undefined;
}

export interface OpenDiffResponse {
  /** A unique identifier for the diff view that was opened. */
  diffId?: string | undefined;
}

export interface GetDocumentTextRequest {
  diffId?: string | undefined;
}

export interface GetDocumentTextResponse {
  content?: string | undefined;
}

export interface ReplaceTextRequest {
  diffId?: string | undefined;
  content?: string | undefined;
  startLine?: number | undefined;
  endLine?: number | undefined;
}

export interface ReplaceTextResponse {
}

export interface ScrollDiffRequest {
  diffId?: string | undefined;
  line?: number | undefined;
}

export interface ScrollDiffResponse {
}

export interface TruncateDocumentRequest {
  diffId?: string | undefined;
  endLine?: number | undefined;
}

export interface TruncateDocumentResponse {
}

export interface CloseAllDiffsRequest {
}

export interface CloseAllDiffsResponse {
}

export interface SaveDocumentRequest {
  diffId?: string | undefined;
}

export interface SaveDocumentResponse {
}

export interface OpenMultiFileDiffRequest {
  title?: string | undefined;
  diffs: ContentDiff[];
}

export interface ContentDiff {
  /** The absolute file path. */
  filePath?: string | undefined;
  leftContent?: string | undefined;
  rightContent?: string | undefined;
}

export interface OpenMultiFileDiffResponse {
}